
# Build and test changes to SeuratWrappers
# Inspired by Jim Hester's Azure Pipelines tests
# https://github.com/jimhester/azuretest

trigger:
- master
- develop

pr:
- master
- develop
- release/*

jobs:
  - job: 'Linux'
    timeoutInMinutes: 30
    pool: Default
    variables:
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
    container: satijalab/seurat:develop
    steps:
      - script: |
          R CMD build .
          R CMD check --as-cran -no-manual Seurat_*
        displayName: 'R CMD Check'
